### ISSUE TITLE
Can't add multiple products to API

### ISSUE THREAD

**Issue by rdeveen** [stephaneey/azure-apim-extension#15]
In API Management i can add multiple products to a API. In the step "API Management - Create or Update API" is can only select one product (or use the product created by previous task) to add to the API. 
Would like to add multiple products to the API.

**Comment by stephaneey** [comment]
Hi,

Indeed, I'll have a look at that one.

Best Regards

**Comment by stephaneey** [comment]
@lurumad  will you be working on this?

**Comment by stephaneey** [comment]
Hello @lurumad ,

Just noticed that you forgot to clear out the products in case you go from two or more to 1 product...the problem was already there but it becomes more visible now that you can associate APIs with multiple prodocuts. I'll update it but leave the issue opened meanwhile.

Best Regards
