### ISSUE TITLE
New API doesn't select OAuth

### ISSUE THREAD

**Issue by leerodgers** [stephaneey/azure-apim-extension#18]
I'm using the create / update API and select Oauth and the selected provider and when it creates the security option is none.  Is this a known issue?

**Comment by stephaneey** [comment]
Hello,

I'm going to have a look at it over the week-end

Best Regards

**Comment by stephaneey** [comment]
Hi,

For some reason (probably due to a merging with a pull request), this part of the code was gone...I re-integrated back and published the updated extension accordingly. In theory, you don't have to change anything on your side and just retry in a few hours from now.

Note that if you use a self-hosted agent and do not see the update, you might want to restart the service and/or worse case, delete the local task folder created in the _work folder as it is not always updated correctly. This is independent of my task of course.

Best Regards

**Comment by leerodgers** [comment]
Thanks!
