### ISSUE TITLE
Generated documentation does not take operation description into account

### ISSUE THREAD

**Issue by Veterini** [stephaneey/azure-apim-extension#30]
Hello,
Your extension has been of great use for us lately but we found some issues concerning the way we want our documentation to look like. As you can see in the link below
[](https://blogs.msdn.microsoft.com/apimanagement/2018/04/11/important-changes-to-openapi-import-and-export/)  the newest version will correct our issue about operation's description.

Would it be difficult to update the call of the extension to the newest version or to provide the user with the means to select the api version?

Thank in advance for your remarks

**Comment by stephaneey** [comment]
Hi Justin,

It might be indeed a good idea to let the user choose the target API version but of course, I don't plan to test all versions so it might also be a source of problems for users...who might thus create issues on the repo just because the code hasn't been tested accordingly. Of course, newer API versions are supposed to be backward compatible but we never know. I'll check your pull request (thanks for that) over the week-end and republish accordingly if everything is all right!

**Comment by jaq316** [comment]
We also want to leverage the newer api version

**Comment by stephaneey** [comment]
Hello,

I guess I'll add the selector to other tasks as well but since I merged @jaq316 's pull request, that should fix it for at list the main apim task.

Thanks
Best Regards
