### ISSUE TITLE
Script overrides host.json file contents of Function app

### ISSUE THREAD

**Issue by lamelyan** [stephaneey/azure-apim-extension#98]
I noticed that when I run a release task 'API Management - Create or Update API on Azure Functions (v1)' 

it overrides the contents of the host.json file of the Function App with `{"swagger":{"enabled":true}}`

I think[ this is the place where it overrides it](https://github.com/stephaneey/azure-apim-extension/blob/master/apimfunction/v3/apimfunction.ps1#L115). Is this correct?  If so, why does it replace the contents of the file and not append to it?

**Comment by stephaneey** [comment]
Hello,

The only thing this task does is to extract the swagger definition from the function app and for this, Swagger must be enabled. However:

- Microsoft has completely changed the way swagger definitions are made available with Function Apps
- The extension only works with the version 1 of Azure Functions which are quite old since we are currently at version 3.

I would strongly encourage you to deal with it differently.

Best Regards

**Comment by lamelyan** [comment]
Ok. I'm using AZ Functions v2 so I'll have to find another way.
